# Generated by Django 3.2.4 on 2021-09-22 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20210920_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 8, 37, 41, 67133, tzinfo=utc)),
        ),
    ]
