# Generated by Django 3.2.4 on 2021-09-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('userlibrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlib',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklib', to='mainapp.books'),
        ),
    ]
